apply plugin: 'java'

group = 'org.spectralmemories'
version = '1.1.0'

repositories {
    mavenCentral()

    maven {
        url = 'https://repo.papermc.io/repository/maven-public/'
    }

    maven {
        url = 'https://maven.enginehub.org/repo/'
    }

    maven {
        url = 'https://mvn.lumine.io/repository/maven-public/'
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.release = 21
    options.encoding = 'UTF-8'
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:1.21.4-R0.1-SNAPSHOT'

    compileOnly 'com.sk89q.worldguard:worldguard-bukkit:7.0.9'

    compileOnly 'io.lumine:Mythic-Dist:5.12.1'

    implementation 'org.yaml:snakeyaml:1.23'
    implementation 'org.jetbrains:annotations:18.0.0'

    implementation(files('libs/SQLAccess.jar'))

    testImplementation platform('org.junit:junit-bom:5.13.4')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

jar {
    archiveBaseName = 'BloodMoon-Reborn'
    archiveVersion = project.version
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from {
        configurations.runtimeClasspath.findAll {
            it.name.endsWith('jar')
        }.collect {
            zipTree(it)
        }
    }
    exclude 'META-INF/*.SF', 'META-INF/*.DSA', 'META-INF/*.RSA'
    preserveFileTimestamps = false
    reproducibleFileOrder = true
}

test {
    useJUnitPlatform()
}

task runSpigot(type: Exec) {
    standardInput = System.in

    workingDir 'exes/server'
    commandLine 'cmd', '/c', 'java', '-jar', file('exes/paper.jar'), 'nogui'
}
